### ISSUE TITLE
A way to copy your active profile pubkey from the extension popup

### ISSUE THREAD

**Issue by blakejakopovic** [ursuscamp/nostore#11]
It would be great to be able to copy your pubkey from this extension popup, as lots of Nostr websites don't support login via extension directly yet.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/427450/235603630-61d7df20-9c89-4182-8b3a-c1ede1617eee.png">

**Comment by ursuscamp** [comment]
This is a good idea, and it's coming in the next release.

**Comment by ursuscamp** [comment]
This has been released. Thanks for the suggestion
