### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by tyiu** [ursuscamp/nostore#18]
It'll help with whoever wants to use this code.

**Comment by vicariousdrama** [comment]
I'm offering a **100_000 sat bounty** to the author of the codebase if they license the project with an open source license before 2024-06-30.

#bounty⚡

**Comment by vicariousdrama** [comment]
@ursuscamp are you able to add a license to this repository to indicate whether or not it is open source for which others may extend and maintain?

**Comment by ursuscamp** [comment]
Thanks for poking me! I have officially open sourced this under the MIT License.
